// English glosses for the flat-en variant, keyed by level-2 slug. A subcategory added later without a gloss keeps its French label.
export const SUBCATEGORY_GLOSSES: Record<string, string> = {
  plomberie: "Plumbing: leaks, taps, toilets, pipes, water heaters, drainage",
  electricite: "Electrical work: wiring, sockets, breakers, power outages in the house, lighting, meters",
  maconnerie: "Masonry: foundations, building walls, concrete slabs and screeds",
  menuiserie: "Carpentry and joinery: wooden doors and furniture, metal gates and welding, aluminium and PVC windows",
  peinture: "House painting: interior and exterior walls, decorative painting, plastering",
  carrelage: "Tiling: floor and wall tiles, bathroom and kitchen tiling",
  climatisation: "Air conditioning and refrigeration: AC install and repair, fridges and freezers, cold rooms",
  toiture: "Roofing: roof leaks, metal roof sheets, gutters",
  terrassement: "Earthworks and site preparation: excavation, levelling, roads and drainage networks",
  vitrerie: "Glazing: broken windows, glass panes, mirrors",
  architecture: "Architecture and engineering studies: house plans, construction supervision",
  genie_civil: "Civil engineering: structures, bridges, large works",
  coiffure: "Hairdressing: women's, men's and children's haircuts, braids, weaves",
  onglerie: "Nail care: manicure, false nails, gel polish",
  maquillage: "Make-up: bridal, evening and professional make-up",
  esthetique: "Beauty and facial care: facials, scrubs, hair removal",
  spa_massage: "Spa and massage: relaxing and therapeutic massage, body treatments",
  barbier: "Barber: beard trim and shave, men's grooming",
  traiteur: "Catering: food for weddings, birthdays and events",
  cuisinier_domicile: "Private cook who cooks at the client's home",
  patisserie: "Pastry: cakes, birthday cakes, pastries",
  boulangerie: "Bakery: bread",
  plats_emporter: "Takeaway meals",
  restauration_evenementielle: "Event food service: buffets and service staff at events",
  menage: "House cleaning: regular cleaning, deep cleaning, after-construction cleaning",
  blanchisserie: "Laundry and dry cleaning, washing and ironing",
  jardinage: "Gardening: garden upkeep, landscaping, tree cutting",
  desinsectisation: "Pest control: cockroaches, mosquitoes, termites, rats and mice",
  conciergerie: "Concierge and errand services",
  garde_enfants: "Childcare: nanny, babysitting, school pick-up",
  garde_personnes_agees: "Care for elderly people",
  aide_domicile: "Home help with daily tasks",
  assistance_pmr: "Assistance for people with reduced mobility",
  transport_personnes: "Passenger transport: taxi, private driver, airport shuttle",
  transport_marchandises: "Goods transport: trucks and vans for cargo",
  demenagement: "Moving house or office",
  location_vehicule: "Vehicle rental",
  livraison_coursier: "Delivery and courier: parcels, documents, meals",
  transport_evenementiel: "Event transport: buses for guests",
  mecanique_automobile: "Car mechanic: diagnostics, servicing, engine repair, car will not start",
  mecanique_moto: "Motorbike mechanic",
  carrosserie: "Car bodywork and car painting",
  pneumatiques: "Tyres: flat tyres, tyre change and repair",
  entretien_auto: "Car maintenance: oil change, car wash, car air conditioning",
  reparation_telephone: "Phone repair: screen, battery, software",
  reparation_ordinateur: "Computer and laptop repair",
  installation_reseau: "Network and Wi-Fi installation",
  developpement_web: "Web and software development: websites, apps",
  formation_informatique: "Computer skills training",
  electronique_hifi: "Electronics and audio repair: TV, radio, speakers, decoders",
  infirmier_domicile: "Home nursing: injections, dressings, home care",
  kinesitherapie: "Physiotherapy and rehabilitation",
  sages_femmes: "Midwife: pregnancy and post-natal care",
  pharmacie_garde: "On-duty pharmacy",
  laboratoire_analyses: "Medical laboratory: blood tests and analyses",
  nutrition: "Nutrition and dietetics",
  accompagnement_psy: "Psychological support and counselling",
  agriculture: "Farming: crops, market gardening, soil preparation",
  elevage: "Livestock: poultry, cattle, pigs",
  veterinaire: "Veterinarian for pets and livestock",
  pisciculture: "Fish farming and fish ponds",
  amenagement_agricole: "Farm development and irrigation",
  transformation_produits: "Processing of farm products",
  soutien_scolaire: "School tutoring and homework help",
  cours_particuliers: "Private lessons: maths, sciences, languages",
  formation_pro: "Vocational and professional training",
  musique_arts: "Music and arts lessons: instruments, singing, drawing",
  coaching: "Coaching and personal development",
  formation_langues: "Language courses: English, French, Lingala and others",
  organisation_evenements: "Event planning: weddings, parties, ceremonies",
  decoration: "Event decoration: venue and hall decoration",
  son_lumiere_dj: "Sound, lighting and DJ for events",
  photographie: "Photography: events, portraits",
  video_montage: "Video filming and editing",
  location_materiel: "Event equipment rental: tents, chairs, tables",
  agent_securite: "Security guards",
  gardiennage: "Property watchmen and guarding, night guard",
  installation_securite: "Security systems: alarms, cameras, access control",
  protection_incendie: "Fire protection: extinguishers, fire safety",
  panneaux_solaires: "Solar panels: installation, maintenance, inverters",
  groupe_electrogene: "Power generators: installation and repair",
  batteries_stockage: "Batteries and energy storage for power cuts",
  audit_energie: "Energy audits and savings",
  biogaz: "Biogas installations",
  couture: "Tailoring and sewing: made-to-measure clothes, alterations, uniforms",
  creation_mode: "Fashion design",
  teinture_wax: "Fabric dyeing and wax prints",
  broderie: "Custom embroidery",
  mercerie: "Haberdashery: sewing supplies",
  impression: "Printing: digital, offset, large format, flyers",
  serigraphie: "Screen printing on t-shirts and objects",
  signaletique: "Signage and shop signs",
  design_graphique: "Graphic design: logos, visual identity",
  communication_digitale: "Digital communication: social media management, online marketing",
  forge_soudure: "Blacksmithing and welding",
  poterie_ceramique: "Pottery and ceramics",
  vannerie: "Basket weaving",
  sculpture: "Sculpture",
  maroquinerie: "Leather goods: bags, shoes, repairs",
  bijouterie: "Jewellery making and repair",
  comptabilite: "Accounting and bookkeeping",
  conseil_juridique: "Legal advice, lawyer",
  fiscalite: "Tax: tax returns and tax advice",
  secretariat_saisie: "Secretarial work and typing",
  traduction: "Translation of documents",
  formalites_admin: "Administrative paperwork: passports, permits, official documents",
};
