// Admin console copy (workstream 08): /admin, its sections and primitives.

const referencedCount = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const adminCopy = {
  meta: { title: "Admin", description: "Centre de contrôle KAYOU." },
  shell: {
    greeting: "Bonjour, administrateur.",
    loading: "Chargement de la console",
  },
  sections: {
    overview: "Vue d'ensemble",
    users: "Communauté",
    providers: "Talents",
    verification: "Vérification",
    bookings: "Réservations",
    reviews: "Avis",
    conversations: "Conversations",
    contacts: "Contact",
    reports: "Modération",
    content: "Contenu",
    categories: "Catégories",
    references: "Listes & lieux",
    audit: "Journal",
    system: "Système",
  },
  common: {
    search: "Rechercher",
    all: "Tous",
    yes: "Oui",
    no: "Non",
    none: "—",
    view: "Voir",
    edit: "Modifier",
    create: "Créer",
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Enregistré",
    cancel: "Annuler",
    close: "Fermer",
    back: "Retour à la liste",
    delete: "Supprimer",
    confirm: "Confirmer",
    reason: "Motif",
    reasonRequired: "Le motif est obligatoire.",
    optional: "facultatif",
    retry: "Réessayer",
    loadError: "Impossible de charger cette section.",
    selectPrompt: "Sélectionnez un élément dans la liste.",
    me: "vous",
    self: "Vous ne pouvez pas modifier votre propre compte.",
    results: (n: number) => (n === 1 ? "1 résultat" : `${n} résultats`),
    page: (page: number, pages: number) => `Page ${page} / ${pages}`,
    previous: "Précédent",
    next: "Suivant",
    openInNewTab: "Ouvrir dans un nouvel onglet",
    since: (date: string) => `Depuis le ${date}`,
    on: (date: string) => `le ${date}`,
    active: "Actif",
    inactive: "Inactif",
    aliases: "Alias",
    aliasesHint: "Séparez les alias par des virgules.",
    source: "Source",
    order: "Ordre",
    label: "Libellé",
    slug: "Slug",
    icon: "Icône",
    color: "Couleur",
    description: "Description",
  },
  pills: {
    PENDING: "En attente",
    CONFIRMED: "Confirmée",
    COMPLETED: "Terminée",
    CANCELLED: "Annulée",
    NEW: "Nouveau",
    READ: "Lu",
    REPLIED: "Répondu",
    CLOSED: "Fermé",
    OPEN: "Ouvert",
    RESOLVED: "Examiné",
    UNDER_REVIEW: "En examen",
    VERIFIED: "Vérifié",
    REJECTED: "Refusé",
    APPROVED: "Approuvé",
    FREE: "Gratuit",
    BOOSTED: "Boosté",
    ELITE: "Élite",
    CLIENT: "Client",
    PROVIDER: "Prestataire",
    ADMIN: "Admin",
    HIDDEN: "Masqué",
    PUBLIC: "Publié",
    SUSPENDED: "Suspendu",
    ACTIVE: "Actif",
    INACTIVE: "Inactif",
    DELETED: "Supprimé",
  },
  errors: {
    referencedCounts: (counts: Record<string, number>) => {
      const parts = [
        counts.providers ? referencedCount(counts.providers, "prestataire", "prestataires") : null,
        counts.bookings ? referencedCount(counts.bookings, "réservation", "réservations") : null,
        counts.leads ? referencedCount(counts.leads, "candidature", "candidatures") : null,
      ].filter(Boolean);
      return parts.length > 0 ? `Références : ${parts.join(", ")}.` : "";
    },
    missingDocs: (kinds: string[]) => `Documents manquants : ${kinds.join(", ")}.`,
  },
  overview: {
    eyebrow: "KAYOU · CONTROL ROOM",
    title: ["Une vue claire.", "Un impact réel."],
    subtitle: "Chaque connexion compte. Suivez votre communauté, accompagnez vos talents et gardez le contrôle.",
    members: "Membres",
    suspended: (n: number) => (n === 1 ? "1 suspendu" : `${n} suspendus`),
    providers: "Talents",
    bookings: "Réservations",
    reports: "Signalements ouverts",
    suggestions: "Propositions de lieux",
    verifications: "Vérifications en attente",
    open: "Ouvrir",
    assistant: "Assistant · conversations aujourd'hui",
    assistantSub: (messages: number, bookings: number, fallback: number | null) =>
      `${messages} message${messages === 1 ? "" : "s"} · ${bookings} réservation${bookings === 1 ? "" : "s"} · repli ${fallback === null ? "—" : `${fallback} %`}`,
    cardTitle: "Une plateforme sous votre contrôle",
    cardBody:
      "Gérez les rôles et suspensions, vérifiez les prestataires, modérez les contenus et consultez la trace des actions administratives. Les compteurs proviennent de votre base de données.",
  },
  users: {
    title: "Communauté",
    subtitle: "Membres, rôles et suspensions.",
    searchPlaceholder: "Nom, e-mail, téléphone, lieu…",
    roleFilter: "Rôle",
    suspendedFilter: "Statut",
    suspendedOnly: "Suspendus",
    activeOnly: "Actifs",
    columns: { member: "Membre", role: "Rôle", place: "Lieu", joined: "Inscrit le", actions: "" },
    promote: "Passer admin",
    demote: "Repasser client",
    roleLocked: "Le rôle d'un prestataire ne change pas ici.",
    suspend: "Suspendre",
    unsuspend: "Réactiver",
    hiddenProvider: "prestataire masqué",
    empty: "Aucun membre ne correspond.",
    toasts: {
      promoted: "Administrateur promu.",
      demoted: "Rôle repassé à client.",
      suspended: "Membre suspendu.",
      unsuspended: "Membre réactivé.",
    },
    sheets: {
      promote: { title: "Promouvoir administrateur", description: "Ce membre aura accès à toute la console.", confirm: "Promouvoir" },
      demote: { title: "Retirer les droits administrateur", description: "Ce membre redevient un client ordinaire.", confirm: "Retirer" },
      suspend: {
        title: "Suspendre ce membre",
        description: "Le membre ne pourra plus se connecter. Son profil prestataire, s'il existe, sera masqué.",
        confirm: "Suspendre",
        reason: "Motif de la suspension",
        placeholder: "Expliquez la raison, visible par le membre.",
      },
      unsuspend: { title: "Réactiver ce membre", description: "Le membre retrouve l'accès à son compte. Un profil prestataire masqué reste masqué.", confirm: "Réactiver" },
    },
  },
  sheet: {
    title: "Fiche membre",
    print: "Imprimer / PDF",
    brand: "KAYOU",
    memberSince: (date: string) => `Membre depuis ${date}`,
    identity: "Identité",
    verified: "Vérifié",
    about: "À propos",
    noAbout: "Aucune description.",
    location: "Localisation & activité",
    phone: "Téléphone",
    whatsapp: "WhatsApp",
    email: "E-mail",
    place: "Lieu",
    address: "Adresse",
    schedule: "Horaires",
    closed: "fermé",
    verification: "Vérification",
    activity: "Activité",
    bookingsAsClient: "Réservations (client)",
    bookingsAsProvider: "Réservations (prestataire)",
    reviewsGiven: "Avis donnés",
    reviewsReceived: "Avis reçus",
    clientRating: "Note client",
    reports: "Signalements",
    reportsLine: (filed: number, against: number) => `${filed} déposés · ${against} reçus`,
    earnings: "Revenus nets",
    lastLogin: "Dernière connexion",
    never: "jamais",
    security: "Sécurité",
    activeAccount: "Compte actif",
    suspendedSince: (date: string) => `Suspendu depuis le ${date}`,
    jobFallback: { provider: "Prestataire de services", member: "Membre KAYOU" },
    years: (n: number) => (n === 1 ? "1 an d'expérience" : `${n} ans d'expérience`),
    skills: "Compétences",
    languages: "Langues",
    modes: "Modes d'intervention",
    pricing: "Tarif indicatif",
    days: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
  },
  providers: {
    title: "Talents",
    subtitle: "Vérification, visibilité et offres des prestataires.",
    searchPlaceholder: "Nom, téléphone, catégorie…",
    verificationFilter: "Vérification",
    tierFilter: "Offre",
    hiddenFilter: "Visibilité",
    hiddenOnly: "Masqués",
    visibleOnly: "Publiés",
    verify: "Vérifier",
    unverify: "Retirer la vérification",
    hide: "Masquer",
    publish: "Publier",
    tier: "Offre",
    premiumUntil: "Jusqu'au",
    premiumUntilHint: "Vide = sans limite.",
    ownerSuspended: "propriétaire suspendu",
    rating: (avg: number, count: number) => `★ ${avg.toFixed(1)} · ${count} avis`,
    jobs: (n: number) => (n === 1 ? "1 prestation" : `${n} prestations`),
    empty: "Aucun prestataire ne correspond.",
    toasts: {
      verified: "Prestataire vérifié.",
      unverified: "Vérification retirée.",
      hidden: "Profil masqué.",
      published: "Profil publié.",
      tier: "Offre mise à jour.",
    },
    sheets: {
      verify: { title: "Vérifier ce prestataire", description: "Le badge « Vérifié » s'affiche sur le profil. Les quatre documents obligatoires doivent être présents.", confirm: "Vérifier" },
      unverify: { title: "Retirer la vérification", description: "Le badge disparaît ; le prestataire pourra renvoyer son dossier.", confirm: "Retirer" },
      hide: { title: "Masquer ce profil", description: "Le profil disparaît de la recherche et des pages publiques.", confirm: "Masquer" },
    },
  },
  verification: {
    title: "Vérification",
    subtitle: "Dossiers KYC des prestataires.",
    statusFilter: "Statut",
    searchPlaceholder: "Nom du prestataire…",
    progress: (approved: number, total: number) => `${approved}/${total} approuvés`,
    submittedOn: (date: string) => `Envoyé le ${date}`,
    notSubmitted: "Non envoyé",
    stats: { underReview: "En examen", verified: "Vérifiés", rejected: "Refusés" },
    documents: "Documents",
    approve: "Approuver",
    reject: "Refuser",
    approved: "Approuvé",
    rejected: "Refusé",
    pending: "À examiner",
    open: "Ouvrir le fichier",
    preview: "Aperçu",
    previewUnavailable: "Aperçu indisponible",
    fileMeta: (mime: string, kb: number) => `${mime} · ${kb} Ko`,
    empty: "Aucun dossier dans cet état.",
    toasts: { approved: "Document approuvé.", rejected: "Document refusé." },
    sheets: {
      reject: { title: "Refuser ce document", description: "Le prestataire verra le motif et pourra remplacer le fichier.", confirm: "Refuser", reason: "Motif du refus", placeholder: "Photo floue, document expiré…" },
    },
  },
  bookings: {
    title: "Réservations",
    subtitle: "Toutes les réservations de la plateforme.",
    searchPlaceholder: "Client, prestataire, téléphone…",
    statusFilter: "Statut",
    columns: { client: "Client", provider: "Prestataire", when: "Date · heure", status: "Statut", actions: "" },
    cancel: "Annuler",
    open: "Ouvrir la réservation",
    empty: "Aucune réservation ne correspond.",
    toasts: { cancelled: "Réservation annulée." },
    sheets: {
      cancel: { title: "Annuler cette réservation", description: "Le client et le prestataire seront notifiés avec le motif.", confirm: "Annuler la réservation", reason: "Motif de l'annulation", placeholder: "Expliquez la raison." },
    },
  },
  reviews: {
    title: "Avis",
    subtitle: "Modération des avis clients.",
    searchPlaceholder: "Auteur, prestataire, commentaire…",
    ratingFilter: "Note",
    stars: (n: number) => `${n} étoile${n > 1 ? "s" : ""}`,
    on: (provider: string, date: string) => `Sur ${provider} · ${date}`,
    reply: "Réponse du prestataire",
    noComment: "Sans commentaire.",
    hide: "Masquer",
    publish: "Publier",
    delete: "Supprimer",
    empty: "Aucun avis ne correspond.",
    toasts: { hidden: "Avis masqué.", published: "Avis publié.", deleted: "Avis supprimé." },
    sheets: {
      delete: { title: "Supprimer cet avis", description: "La note moyenne du prestataire sera recalculée. Cette action est définitive.", confirm: "Supprimer" },
    },
  },
  conversations: {
    title: "Conversations",
    subtitle: "Échanges entre clients et prestataires.",
    searchPlaceholder: "Sujet, participant…",
    noSubject: "Sans sujet",
    parties: (client: string, provider: string) => `Client : ${client} · Prestataire : ${provider}`,
    messages: (n: number) => (n === 1 ? "1 message" : `${n} messages`),
    deleteConversation: "Supprimer la conversation",
    deleteMessage: "Supprimer ce message",
    deletedMessage: "Message supprimé",
    attachment: (kind: string) => (kind === "audio" ? "Message vocal" : "Image"),
    empty: "Aucune conversation.",
    emptyThread: "Aucun message.",
    toasts: { conversationDeleted: "Conversation supprimée.", messageDeleted: "Message supprimé." },
    sheets: {
      deleteConversation: { title: "Supprimer la conversation", description: "Tous les messages seront supprimés pour les deux participants.", confirm: "Supprimer" },
      deleteMessage: { title: "Supprimer ce message", description: "Le message est remplacé par « Message supprimé » pour les deux participants.", confirm: "Supprimer" },
    },
  },
  contacts: {
    title: "Contact",
    subtitle: "Messages reçus par le formulaire de contact.",
    searchPlaceholder: "Nom, e-mail, sujet…",
    statusFilter: "Statut",
    markReplied: "Marquer répondu",
    close: "Fermer",
    reopen: "Rouvrir",
    delete: "Supprimer",
    receivedOn: (date: string) => `Reçu le ${date}`,
    empty: "Aucun message.",
    toasts: { updated: "Statut mis à jour.", deleted: "Message supprimé." },
    sheets: {
      delete: { title: "Supprimer ce message", description: "Le message disparaît définitivement de la boîte de réception.", confirm: "Supprimer" },
    },
  },
  reports: {
    title: "Confiance & sécurité",
    subtitle: "Examinez les signalements puis intervenez dans l'onglet concerné.",
    showResolved: "Afficher les examinés",
    showOpen: "Afficher les ouverts",
    kinds: { USER: "Membre", PROVIDER: "Prestataire", REVIEW: "Avis", MESSAGE: "Message", CONVERSATION: "Conversation" },
    reporter: (name: string) => `Signalé par ${name}`,
    target: "Cible",
    targetMissing: "cible supprimée",
    viewTarget: "Voir la cible",
    resolve: "Marquer comme examiné",
    resolution: "Résolution",
    resolvedBy: (date: string) => `Examiné le ${date}`,
    empty: "Aucun signalement ouvert",
    emptyResolved: "Aucun signalement examiné",
    emptyDescription: "Les signalements des membres apparaissent ici.",
    toasts: { resolved: "Signalement marqué comme examiné." },
    sheets: {
      resolve: { title: "Marquer comme examiné", description: "Notez ce qui a été fait ; la note reste dans le journal.", confirm: "Marquer examiné", reason: "Résolution", placeholder: "Numéro vérifié avec le prestataire…" },
    },
  },
  content: {
    title: "Contenu",
    subtitle: "Textes de la page d'accueil, coordonnées et fonctionnalités.",
    emptyHint: "Laissez vide pour utiliser le texte par défaut.",
    groups: {
      hero: "Section Hero",
      how: "Comment ça marche",
      premium: "Section mise en avant",
      contact: "Coordonnées",
      features: "Fonctionnalités activées",
      maintenance: "Mode maintenance",
    },
    fields: {
      hero_title: "Titre",
      hero_subtitle: "Sous-titre",
      hero_cta: "Bouton d'action",
      tagline: "Accroche",
      how1_title: "Étape 1 · titre",
      how1_desc: "Étape 1 · description",
      how2_title: "Étape 2 · titre",
      how2_desc: "Étape 2 · description",
      how3_title: "Étape 3 · titre",
      how3_desc: "Étape 3 · description",
      premium_title: "Titre",
      premium_subtitle: "Sous-titre",
      contact_phone: "Téléphone",
      contact_email: "E-mail",
      contact_website: "Site web",
      maintenance_message: "Message affiché",
    },
    toggles: {
      feat_booking: { label: "Réservations", description: "Les clients peuvent réserver un créneau." },
      feat_reviews: { label: "Avis", description: "Les clients peuvent laisser un avis après une prestation." },
      feat_whatsapp: { label: "WhatsApp", description: "Le bouton WhatsApp s'affiche sur les profils." },
      feat_jev_search: { label: "Recherche comprise", description: "La recherche ajoute le service que le client décrit, par exemple Plomberie pour « fuite d'eau ». Utilise Jev (TypeSafe)." },
      contacts_require_premium: { label: "Contacts réservés au premium", description: "Les coordonnées des prestataires gratuits sont masquées aux visiteurs." },
      maintenance_mode: { label: "Maintenance", description: "Affiche un bandeau de maintenance sur toutes les pages." },
    },
    save: "Enregistrer les modifications",
    saved: "Modifications enregistrées",
    nothingToSave: "Aucune modification.",
  },
  categories: {
    title: "Catégories",
    subtitle: "Arborescence à trois niveaux : catégorie › sous-catégorie › service.",
    level1: "Catégories",
    level2: "Sous-catégories",
    level3: "Services",
    newCategory: "Nouvelle catégorie",
    newSubcategory: "Nouvelle sous-catégorie",
    newService: "Nouveau service",
    editCategory: "Modifier la catégorie",
    editNode: "Modifier",
    selectCategory: "Sélectionnez une catégorie.",
    selectSubcategory: "Sélectionnez une sous-catégorie.",
    noChildren: "Aucun élément.",
    counts: (c: { providers: number; bookings: number; leads: number }) => `${c.providers} prest. · ${c.bookings} rés. · ${c.leads} cand.`,
    activate: "Activer",
    deactivate: "Désactiver",
    delete: "Supprimer",
    name: "Nom",
    parent: "Parent",
    active: "Actif (visible dans les listes publiques)",
    iconPlaceholder: "Choisir une icône",
    iconSearch: "Rechercher une icône…",
    iconClear: "Effacer",
    iconNone: "Aucune icône trouvée.",
    iconMore: "Affinez la recherche pour voir d'autres icônes.",
    colorHint: "Classe Tailwind ou nom de couleur, par ex. emerald.",
    toasts: { created: "Élément créé.", updated: "Élément mis à jour.", deleted: "Élément supprimé.", activated: "Élément activé.", deactivated: "Élément désactivé." },
    sheets: {
      deactivate: { title: "Désactiver cet élément", description: "Il disparaît des listes publiques. Refusé s'il est encore utilisé.", confirm: "Désactiver" },
      delete: { title: "Supprimer cet élément", description: "Suppression définitive. Refusée si des prestataires, réservations ou candidatures y sont rattachés.", confirm: "Supprimer" },
    },
  },
  references: {
    title: "Listes & lieux",
    subtitle: "Référentiels utilisés par les formulaires et la recherche.",
    tabs: { places: "Lieux", lists: "Listes" },
  },
  places: {
    suggestions: (n: number) => `Propositions à valider (${n})`,
    suggestedBy: (name: string, date: string) => `Proposé par ${name} · ${date}`,
    review: "Examiner",
    reject: "Refuser",
    approve: "Approuver la proposition",
    approveHint: "Vérifiez le libellé puis approuvez : le lieu est créé et le membre notifié.",
    noSuggestions: "Aucune proposition en attente.",
    form: { create: "Nouveau lieu", edit: "Modifier le lieu", kind: "Type", parent: "Rattaché à", parentHint: "Choisissez le lieu parent dans la cascade.", noParent: "Aucun (pays)", latitude: "Latitude", longitude: "Longitude", active: "Actif", chain: "Rattachement" },
    kindsFilter: "Type",
    searchPlaceholder: "Rechercher un lieu…",
    list: "Lieux",
    children: (n: number) => (n === 1 ? "1 subdivision" : `${n} subdivisions`),
    mergedInto: (label: string) => `→ ${label}`,
    merge: "Fusionner",
    mergeTitle: "Fusionner deux lieux",
    mergeFrom: "Lieu à fusionner",
    mergeInto: "Dans",
    mergeHint: "Les membres, prestataires, adresses et réservations du premier sont repointés vers le second.",
    mergeConfirm: "Fusionner",
    empty: "Aucun lieu.",
    toasts: {
      created: "Lieu créé.",
      updated: "Lieu mis à jour.",
      approved: "Proposition approuvée.",
      rejected: "Proposition refusée.",
      merged: (n: number) => `Lieux fusionnés · ${n} éléments repointés.`,
    },
    sheets: {
      reject: { title: "Refuser la proposition", description: "Le membre sera notifié du refus.", confirm: "Refuser" },
      merge: { title: "Fusionner ces lieux", description: "Le premier est désactivé et pointe vers le second. Irréversible.", confirm: "Fusionner" },
    },
  },
  lists: {
    types: { LANGUAGE: "Langue", INTERVENTION_MODE: "Mode d'intervention", CURRENCY: "Devise", PRICE_UNIT: "Unité de prix", SKILL: "Compétence" },
    form: { create: "Nouvel élément", edit: "Modifier l'élément", type: "Type", category: "Catégorie (compétences)", categoryAny: "Toutes les catégories", suggested: "Proposé dans les formulaires", suggestedHint: "Apparaît dans les choix proposés aux prestataires.", active: "Actif" },
    searchPlaceholder: "Rechercher…",
    list: "Éléments",
    usage: (n: number) => (n === 1 ? "1 utilisation" : `${n} utilisations`),
    merge: "Fusionner",
    mergeTitle: "Fusionner deux éléments",
    mergeFrom: "Élément à fusionner",
    mergeInto: "Dans",
    mergeHint: "Les prestataires qui utilisent le premier sont repointés vers le second.",
    empty: "Aucun élément.",
    toasts: { created: "Élément créé.", updated: "Élément mis à jour.", merged: (n: number) => `Éléments fusionnés · ${n} liens repointés.` },
    sheets: { merge: { title: "Fusionner ces éléments", description: "Le premier est désactivé et pointe vers le second. Irréversible.", confirm: "Fusionner" } },
  },
  audit: {
    title: "Journal des actions",
    subtitle: "Les 200 dernières actions administratives, enregistrées côté serveur.",
    columns: { action: "Action", actor: "Auteur", target: "Cible", date: "Date" },
    system: "Système",
    details: "Détails",
    empty: "Aucune action enregistrée.",
  },
  system: {
    title: "État du système",
    subtitle: "Santé des services et version déployée.",
    database: "Base de données",
    storage: "Stockage",
    email: "E-mail",
    version: "Version",
    commit: "Commit",
    webMode: "Mode web",
    node: "Node",
    ok: "Opérationnel",
    error: "En erreur",
    notConfigured: "Non configuré",
    unknown: "Inconnu",
  },
} as const;
