// Assistant concierge copy (docs/ai-agents, phase 1). Components never inline French.

export const assistantCopy = {
  meta: {
    title: "Assistant KAYOU",
    description: "Décrivez votre besoin, l'assistant KAYOU vous propose les bons prestataires et leurs créneaux.",
  },
  nav: {
    label: "Assistant",
  },
  hero: {
    link: "Ou décrivez votre besoin à l'assistant",
  },
  header: {
    eyebrow: "Assistant KAYOU",
    title: "Assistant",
    subtitle: "Dites ce dont vous avez besoin, il trouve les prestataires et leurs créneaux.",
  },
  greeting: {
    title: (firstName: string | null) => (firstName ? `Bonjour ${firstName}. De quoi avez-vous besoin ?` : "Bonjour. De quoi avez-vous besoin ?"),
    body: "Décrivez le service, votre commune et le moment souhaité. Je vous propose les bons prestataires et leurs créneaux réels.",
    chipsLabel: "Suggestions",
  },
  chips: [
    "Un plombier pour une fuite à Gombe",
    "Un électricien à Limete demain",
    "Ménage cette semaine à Ngaliema",
    "Une coiffeuse à domicile à Kalamu",
    "Un mécanicien à Masina",
    "Un peintre pour un salon à Lemba",
    "Garde d'enfants le week-end à Gombe",
    "Un plombier à Brazzaville",
  ],
  chipsNearMe: [
    "Un plombier près de chez moi",
    "Un électricien près de chez moi",
    "Ménage cette semaine près de chez moi",
    "Une coiffeuse à domicile près de chez moi",
  ],
  composer: {
    label: "Votre demande",
    placeholder: "Ex : un plombier pour une fuite à Gombe demain matin",
    send: "Envoyer",
    hint: "L'assistant propose, vous décidez. Rien n'est réservé sans vous.",
  },
  thinking: "L'assistant cherche…",
  error: {
    title: "La réponse a été interrompue.",
    body: "Vérifiez votre connexion, puis réessayez ou reformulez votre demande.",
    retry: "Réessayer",
  },
  unavailable: {
    title: "L'assistant est indisponible pour le moment.",
    body: "Réessayez dans un instant, ou trouvez un prestataire directement dans la recherche.",
    retry: "Réessayer",
    search: "Ouvrir la recherche",
  },
  tools: {
    place: (label: string) => `Lieu retenu : ${label}`,
    placeMissing: "Aucun lieu ne correspond.",
    searching: "Recherche de prestataires",
    searchError: "La recherche n'a pas abouti.",
    widened: "Aucun résultat à ce niveau, recherche élargie.",
    detailError: "Impossible de charger ce prestataire.",
    availabilityError: "Impossible de charger les créneaux.",
    activityError: "Impossible de charger votre activité.",
  },
  pick: {
    choose: "Choisir",
    chosen: "Choisi",
    count: (n: number, total: number) =>
      total > n ? `${n} prestataires proposés sur ${total}` : n === 1 ? "1 prestataire proposé" : `${n} prestataires proposés`,
    empty: {
      title: "Aucun prestataire pour cette demande",
      body: "L'assistant élargit la zone ou la catégorie. Vous pouvez aussi ouvrir la recherche.",
      action: "Ouvrir la recherche",
    },
    chooseMessage: (name: string) => `Je choisis ${name}`,
  },
  detail: {
    experience: (years: number) => (years === 1 ? "1 an d'expérience" : `${years} ans d'expérience`),
    reviews: (n: number) => (n === 1 ? "1 avis" : `${n} avis`),
    jobs: (n: number) => (n === 1 ? "1 prestation" : `${n} prestations`),
    schedule: "Horaires",
    closed: "Fermé",
    skills: "Compétences",
    pricing: "Tarif indicatif",
    pricingFrom: (amount: string, unit: string) => (unit ? `à partir de ${amount} · ${unit}` : `à partir de ${amount}`),
    unavailable: "Ne prend pas de réservations pour le moment",
    call: "Appeler",
    whatsapp: "WhatsApp",
    slots: "Voir les créneaux",
    write: "Écrire",
    book: "Réserver",
    profile: "Voir le profil",
    slotsMessage: (name: string) => `Quels sont les créneaux de ${name} ?`,
    blocked: "Les échanges avec ce prestataire sont désactivés.",
  },
  availability: {
    title: "Créneaux disponibles",
    dates: "Dates",
    slots: "Créneau",
    empty: "Aucun créneau ce jour",
    timezone: (tz: string) => `Horaires : ${tz}`,
    duration: (minutes: number) => `Créneaux de ${minutes} min`,
    book: "Réserver ce créneau",
    bookHint: "L'assistant prépare la demande ; vous la confirmez avant l'envoi. Le prestataire confirme ensuite.",
    pickMessage: (dateLabel: string, time: string) => `Je préfère le ${dateLabel} à ${time}, réserve ce créneau`,
  },
  approval: {
    bookingTitle: "Demande de réservation à envoyer",
    bookingHint: "Rien n'est envoyé sans vous. Le prestataire devra ensuite confirmer.",
    provider: "Prestataire",
    when: "Date et heure",
    timezone: (tz: string) => `Heure locale du prestataire (${tz})`,
    phone: "Téléphone",
    address: "Adresse",
    addressNone: "Sans adresse",
    addressSaved: (label: string) => `Adresse enregistrée « ${label} »`,
    notes: "Précisions",
    confirm: "Confirmer",
    cancel: "Annuler",
    sending: "Envoi…",
    messageTitle: "Message à envoyer",
    messageHint: "Relisez ou modifiez le texte. Il part dans votre messagerie KAYOU.",
    messageLabel: "Votre message",
    subject: "Sujet",
    counter: (n: number, max: number) => `${n}/${max}`,
    send: "Envoyer",
    sendRevised: "Envoyer le texte modifié",
    empty: "Écrivez un message avant d'envoyer.",
    denied: "Annulé, rien n'a été envoyé.",
    superseded: "Remplacé par votre message suivant.",
    answered: "Accord donné, envoi en cours…",
    cancelReason: "Le client a annulé cette action.",
    revisedMessage: (text: string) => `Envoie plutôt ce message au prestataire, tel quel : « ${text} »`,
  },
  status: {
    bookingTitle: "Demande envoyée",
    bookingBody: "Le prestataire doit confirmer. Vous serez notifié dès sa réponse.",
    bookingLink: "Voir la réservation",
    messageTitle: "Message envoyé",
    messageBody: (name: string) => `${name} le lira dans la messagerie KAYOU.`,
    messageLink: "Ouvrir la conversation",
    errorTitle: "Action impossible",
    slotTaken: "Ce créneau vient d'être pris. L'assistant recharge les disponibilités.",
  },
  activity: {
    title: "Votre activité",
    bookings: "Réservations en cours",
    conversations: "Conversations",
    addresses: "Adresses",
    empty: "Rien en cours pour le moment.",
    open: "Ouvrir",
  },
  addressCard: {
    title: "Adresse de la prestation",
    hint: "Choisissez une adresse enregistrée ou saisissez-en une nouvelle.",
    pick: (label: string, line: string) => `Utilise mon adresse « ${label} » : ${line}`,
    new: "Nouvelle adresse",
    line: "Adresse",
    location: "Commune ou quartier",
    save: "Utiliser cette adresse",
    saving: "Enregistrement…",
    saveDefault: "Enregistrer comme adresse par défaut",
    saveDefaultTitle: (place: string) => `Enregistrer ${place} comme votre adresse ?`,
    saveDefaultHint: "L'assistant ne vous redemandera plus où chercher.",
    saved: (line: string) => `J'ai enregistré mon adresse : ${line}`,
    newMessage: (line: string) => `Nouvelle adresse pour la prestation : ${line}`,
    lineRequired: "Indiquez l'adresse.",
    labels: { HOME: "Domicile", WORK: "Travail", OTHER: "Autre" } as Record<string, string>,
  },
  caps: {
    daily: "Vous avez atteint la limite de demandes pour aujourd'hui.",
    fullTitle: "Cette conversation est longue.",
    fullBody: "Ouvrez une nouvelle conversation pour continuer avec l'assistant.",
    newConversation: "Nouvelle conversation",
    archivedTitle: "Conversation archivée.",
  },
  conversations: {
    untitled: "Nouvelle conversation",
    trigger: "Conversations",
    new: "Nouvelle conversation",
    newShort: "Nouvelle",
    archive: "Archiver cette conversation",
    sheetTitle: "Mes conversations",
    close: "Fermer",
    active: "Actives",
    archived: "Archivées",
    count: (n: number) => `${n}`,
    more: "Voir plus",
    noPreview: "Aucun message texte",
    rowMenu: (title: string) => `Actions pour « ${title} »`,
    actions: {
      open: "Ouvrir",
      rename: "Renommer",
      archive: "Archiver",
      unarchive: "Réactiver",
      delete: "Supprimer",
    },
    rename: {
      label: "Titre de la conversation",
      save: "Enregistrer",
      cancel: "Annuler",
      reset: "Titre automatique",
      counter: (n: number, max: number) => `${n}/${max}`,
    },
    delete: {
      title: "Supprimer cette conversation ?",
      body: "Les messages échangés avec l'assistant seront supprimés définitivement. Vos réservations et vos conversations avec les prestataires restent intactes dans « Mes réservations » et la messagerie.",
      confirm: "Supprimer",
      cancel: "Annuler",
    },
    empty: {
      title: "Aucune conversation pour le moment",
      body: "Vos échanges avec l'assistant apparaîtront ici dès votre première demande.",
      action: "Écrire à l'assistant",
    },
    archivedEmpty: "Aucune conversation archivée.",
    loading: "Chargement des conversations",
    loadError: "Impossible de charger vos conversations.",
    retry: "Réessayer",
    readOnly: {
      title: "Conversation archivée",
      body: "Elle est en lecture seule. Réactivez-la pour reprendre l'échange.",
      action: "Réactiver",
    },
    toasts: {
      archived: "Conversation archivée.",
      unarchived: "Conversation réactivée.",
      renamed: "Titre enregistré.",
      deleted: "Conversation supprimée. Vos réservations sont conservées.",
      notFound: "Cette conversation est introuvable. Voici votre conversation en cours.",
      failed: "L'action n'a pas abouti. Réessayez.",
    },
  },
  personalChips: {
    label: "Suggestions personnelles",
  },
} as const;
