// Assistant concierge copy (docs/ai-agents, phase 1). Components never inline French.

export const assistantCopy = {
  meta: {
    title: "Assistant KAYOU",
    description: "Décrivez votre besoin, l'assistant KAYOU vous propose les bons prestataires et leurs créneaux.",
  },
  nav: {
    label: "Assistant",
  },
  hero: {
    link: "Ou décrivez votre besoin à l'assistant",
  },
  header: {
    eyebrow: "Assistant KAYOU",
    title: "Assistant",
    subtitle: "Dites ce dont vous avez besoin, il trouve les prestataires et leurs créneaux.",
  },
  greeting: {
    title: (firstName: string | null) => (firstName ? `Bonjour ${firstName}. De quoi avez-vous besoin ?` : "Bonjour. De quoi avez-vous besoin ?"),
    body: "Décrivez le service, votre commune et le moment souhaité. Je vous propose les bons prestataires et leurs créneaux réels.",
    chipsLabel: "Suggestions",
  },
  chips: [
    "Un plombier pour une fuite à Gombe",
    "Un électricien à Limete demain",
    "Ménage cette semaine à Ngaliema",
    "Une coiffeuse à domicile à Kalamu",
    "Un mécanicien à Masina",
    "Un peintre pour un salon à Lemba",
    "Garde d'enfants le week-end à Gombe",
    "Un plombier à Brazzaville",
  ],
  chipsNearMe: [
    "Un plombier près de chez moi",
    "Un électricien près de chez moi",
    "Ménage cette semaine près de chez moi",
    "Une coiffeuse à domicile près de chez moi",
  ],
  composer: {
    label: "Votre demande",
    placeholder: "Ex : un plombier pour une fuite à Gombe demain matin",
    send: "Envoyer",
    hint: "L'assistant propose, vous décidez. Rien n'est réservé sans vous.",
  },
  thinking: "L'assistant cherche…",
  error: {
    title: "La réponse a été interrompue.",
    body: "Vérifiez votre connexion, puis réessayez ou reformulez votre demande.",
    retry: "Réessayer",
  },
  unavailable: {
    title: "L'assistant est indisponible pour le moment.",
    body: "Réessayez dans un instant, ou trouvez un prestataire directement dans la recherche.",
    retry: "Réessayer",
    search: "Ouvrir la recherche",
  },
  tools: {
    place: (label: string) => `Lieu retenu : ${label}`,
    placeMissing: "Aucun lieu ne correspond.",
    searching: "Recherche de prestataires",
    searchError: "La recherche n'a pas abouti.",
    widened: "Aucun résultat à ce niveau, recherche élargie.",
    detailError: "Impossible de charger ce prestataire.",
    availabilityError: "Impossible de charger les créneaux.",
  },
  pick: {
    choose: "Choisir",
    chosen: "Choisi",
    count: (n: number, total: number) =>
      total > n ? `${n} prestataires proposés sur ${total}` : n === 1 ? "1 prestataire proposé" : `${n} prestataires proposés`,
    empty: {
      title: "Aucun prestataire pour cette demande",
      body: "L'assistant élargit la zone ou la catégorie. Vous pouvez aussi ouvrir la recherche.",
      action: "Ouvrir la recherche",
    },
    chooseMessage: (name: string) => `Je choisis ${name}`,
  },
  detail: {
    experience: (years: number) => (years === 1 ? "1 an d'expérience" : `${years} ans d'expérience`),
    reviews: (n: number) => (n === 1 ? "1 avis" : `${n} avis`),
    jobs: (n: number) => (n === 1 ? "1 prestation" : `${n} prestations`),
    schedule: "Horaires",
    closed: "Fermé",
    skills: "Compétences",
    pricing: "Tarif indicatif",
    pricingFrom: (amount: string, unit: string) => (unit ? `à partir de ${amount} · ${unit}` : `à partir de ${amount}`),
    unavailable: "Ne prend pas de réservations pour le moment",
    call: "Appeler",
    whatsapp: "WhatsApp",
    slots: "Voir les créneaux",
    write: "Écrire",
    book: "Réserver",
    profile: "Voir le profil",
    slotsMessage: (name: string) => `Quels sont les créneaux de ${name} ?`,
    blocked: "Les échanges avec ce prestataire sont désactivés.",
  },
  availability: {
    title: "Créneaux disponibles",
    dates: "Dates",
    slots: "Créneau",
    empty: "Aucun créneau ce jour",
    timezone: (tz: string) => `Horaires : ${tz}`,
    duration: (minutes: number) => `Créneaux de ${minutes} min`,
    book: "Réserver ce créneau",
    bookHint: "La réservation se termine sur la page du prestataire. Il confirme ensuite.",
    pickMessage: (dateLabel: string, time: string) => `Je préfère le ${dateLabel} à ${time}`,
  },
} as const;
