// Auth screens copy (workstream 06): welcome carousel, login, register and the shared OTP steps.

export const authCopy = {
  welcome: {
    title: "Bienvenue",
    skip: "Passer",
    next: "Continuer",
    start: "Commencer",
    haveAccount: "J'ai déjà un compte",
    slideOf: (n: number, total: number) => `Diapositive ${n} sur ${total}`,
    slides: [
      {
        title: "Les services dont vous avez besoin, les professionnels qu'il vous faut.",
        description: "Trouvez, réservez et suivez vos services en toute simplicité.",
        image: "/welcome/slide-1.png",
      },
      {
        title: "Réservez en quelques gestes.",
        description: "Comparez les profils, choisissez votre créneau et confirmez en un instant.",
        image: "/welcome/slide-2.png",
      },
      {
        title: "Des pros vérifiés, à votre porte.",
        description: "Des prestataires vérifiés se déplacent chez vous, prêts à intervenir.",
        image: "/welcome/slide-3.png",
      },
      {
        title: "Votre avis compte.",
        description: "Notez et partagez votre expérience pour aider toute la communauté.",
        image: "/welcome/slide-4.png",
      },
    ],
  },
  login: {
    meta: { title: "Connexion", description: "Connectez-vous à KAYOU avec votre numéro de téléphone." },
    title: "Bienvenue sur KAYOU",
    subtitle: "Retrouvez vos services et vos réservations.",
    footerQuestion: "Nouveau ici ?",
    footerAction: "Créer un compte",
  },
  register: {
    meta: { title: "Créer un compte", description: "Rejoignez KAYOU en quelques secondes avec votre numéro." },
    eyebrow: "LES BELLES RENCONTRES COMMENCENT ICI",
    title: "Faites le premier pas.",
    subtitle: "Trouvez un talent. Faites grandir le vôtre.",
    footerQuestion: "Déjà membre ?",
    footerAction: "Se connecter",
    accountType: {
      legend: "Type de compte",
      client: "Je cherche un service",
      provider: "Je propose mes talents",
    },
  },
  steps: {
    phone: "Numéro",
    otp: "Code",
    name: "Identité",
    terms: "Conditions",
    progress: (n: number, total: number) => `Étape ${n} sur ${total}`,
  },
  phone: {
    country: "Pays",
    countries: [
      { code: "CD" as const, dial: "+243", label: "RD Congo", hint: "Ex. : 81 234 56 78" },
      { code: "CG" as const, dial: "+242", label: "Congo-Brazzaville", hint: "Ex. : 06 123 45 67" },
    ],
    label: "Numéro de téléphone",
    placeholder: "Votre numéro",
    hint: "Un code à 6 chiffres vous sera envoyé par SMS.",
    submit: "Recevoir le code",
    sending: "Envoi du code…",
    invalid: "Ce numéro ne semble pas valide pour le pays choisi.",
  },
  otp: {
    title: "Entrez le code reçu",
    sentTo: (phone: string) => `Code envoyé au ${phone}.`,
    label: "Code de vérification",
    digit: (n: number) => `Chiffre ${n}`,
    submit: "Se connecter",
    verifying: "Vérification…",
    resend: "Renvoyer le code",
    resendIn: (seconds: number) => `Renvoyer le code dans ${seconds} s`,
    resent: "Nouveau code envoyé.",
    changeNumber: "Modifier le numéro",
    incomplete: "Saisissez les 6 chiffres du code.",
  },
  name: {
    title: "Faisons connaissance",
    subtitle: "Ces informations apparaissent sur vos réservations.",
    firstName: "Prénom",
    lastName: "Nom",
    location: "Où êtes-vous ?",
    submit: "Continuer",
    saving: "Enregistrement…",
    required: "Indiquez votre prénom et votre nom.",
  },
  terms: {
    title: "Une dernière étape",
    subtitle: "Pour utiliser KAYOU, merci d'accepter nos conditions.",
    accept: "J'accepte les",
    cgu: "conditions générales d'utilisation",
    and: "et la",
    privacy: "politique de confidentialité",
    end: "de KAYOU.",
    submit: "Accepter et continuer",
    saving: "Enregistrement…",
  },
  errors: {
    invalidPhone: "Numéro invalide. Vérifiez l'indicatif et le numéro.",
    wrongCode: "Code incorrect. Vérifiez les chiffres saisis.",
    expiredCode: "Ce code a expiré. Demandez-en un nouveau.",
    rateLimited: "Trop de tentatives. Patientez un instant avant de réessayer.",
    smsFailed: "Le SMS n'a pas pu être envoyé. Réessayez dans un instant.",
    sessionMissing: "La connexion a échoué. Réessayez.",
    generic: "Une erreur est survenue. Réessayez.",
  },
  demo: {
    eyebrow: "Accès rapide (dev)",
    description: "Comptes de démonstration seedés. Absent en production.",
    toggle: "Comptes de démonstration",
    signingIn: "Connexion…",
    accounts: [
      { role: "Client", name: "Paul Kabasele", email: "paul.kabasele@email.cd", hint: "Réservations et messages" },
      { role: "Prestataire", name: "Jean-Pierre Mukendi", email: "jeanpierre.mukendi@kayou.cd", hint: "Profil pro et planning" },
      { role: "Admin", name: "Admin KAYOU", email: "admin@kayou.cd", hint: "Console d'administration" },
    ],
  },
} as const;

export type PhoneCountryCode = (typeof authCopy.phone.countries)[number]["code"];
