// Bookings copy (workstream 07): /mes-reservations, /reservation/[id], BookingCard, BookingActions, ClientRatingForm.

export const bookingsCopy = {
  meta: {
    title: "Mes commandes",
    description: "Suivez vos réservations en cours, terminées et annulées sur KAYOU.",
  },
  list: {
    title: "Mes commandes",
    backLabel: "Retour à l'accueil",
    tabs: {
      all: "Toutes",
      active: "En cours",
      completed: "Terminées",
      cancelled: "Annulées",
    },
    empty: {
      title: "Aucune commande",
      description: "Vos réservations apparaîtront ici dès que vous aurez réservé un prestataire.",
      action: "Rechercher",
    },
    emptyFiltered: "Aucune commande dans cette catégorie.",
    cancelled: "Réservation annulée",
  },
  card: {
    date: "Date",
    time: "Heure",
    duration: (min: number) => (min >= 60 ? `${Math.floor(min / 60)} h${min % 60 ? ` ${min % 60}` : ""}` : `${min} min`),
    notes: "Notes",
    clientRating: (avg: number, count: number) => `Note client ${avg.toFixed(1)} (${count})`,
    noCategory: "Prestation",
    viewDetail: "Voir le détail",
    agreedPrice: "Prix convenu",
    paid: "Payé en espèces",
    unpaid: "Non payé",
    cancelReason: "Motif",
  },
  actions: {
    cancel: "Annuler",
    confirm: "Confirmer",
    complete: "Terminer",
    cancelTitle: "Annuler cette réservation ?",
    cancelDescriptionClient: "Le prestataire sera prévenu de l'annulation.",
    cancelDescriptionProvider: "Indiquez au client pourquoi vous annulez.",
    cancelReasonLabel: "Motif de l'annulation",
    cancelReasonPlaceholder: "Ex : indisponible ce jour-là",
    cancelConfirm: "Annuler la réservation",
    cancelKeep: "Garder",
    confirmTitle: "Confirmer cette réservation ?",
    confirmDescription: "Le client recevra une notification de confirmation.",
    confirmConfirm: "Confirmer",
    completeTitle: "Marquer comme terminée",
    completeDescription: "Indiquez le prix convenu avec le client, si vous le souhaitez.",
    agreedPriceLabel: "Prix convenu (FC)",
    agreedPricePlaceholder: "Ex : 25000",
    agreedPriceHint: "Montant en francs congolais, sans décimales.",
    paidLabel: "Payé en espèces",
    completeConfirm: "Terminer",
    toasts: {
      cancelled: "Réservation annulée",
      confirmed: "Réservation confirmée",
      completed: "Réservation terminée",
    },
  },
  clientRating: {
    title: "Noter ce client",
    ratingLabel: "Votre note",
    commentLabel: "Commentaire (optionnel)",
    commentPlaceholder: "Ponctualité, communication, respect des consignes…",
    counter: (n: number, max: number) => `${n}/${max}`,
    submit: "Envoyer ma note",
    submitting: "Envoi…",
    thanks: "Merci, votre note a été enregistrée.",
    star: (n: number) => (n === 1 ? "1 étoile" : `${n} étoiles`),
  },
  detail: {
    meta: {
      title: "Réservation",
      description: "Détail d'une réservation KAYOU.",
    },
    title: "Réservation",
    backLabel: "Retour à mes réservations",
    viewProfile: "Voir le profil",
    address: "Adresse",
    clientPhone: "Téléphone du client",
    call: "Appeler",
    notes: "Notes du client",
    noNotes: "Aucune note.",
    agreedPrice: "Prix convenu",
    net: (amount: string) => `Net pour vous : ${amount}`,
    internalNotes: "Notes internes",
    internalNotesHint: "Visibles uniquement par vous.",
    internalNotesPlaceholder: "Ex : apporter l'échelle, code du portail…",
    saveNotes: "Enregistrer",
    notesSaved: "Notes enregistrées",
    timeline: "Historique",
    events: {
      created: "Réservation créée",
      confirmed: "Confirmée par le prestataire",
      completed: "Prestation terminée",
      cancelled: "Annulée",
      reason: (reason: string) => `Motif : ${reason}`,
    },
    review: "Avis du client",
    clientReview: "Votre note du client",
    notFound: {
      title: "Réservation introuvable",
      description: "Cette réservation n'existe pas ou ne vous concerne pas.",
      action: "Retour",
    },
  },
} as const;
