// Account copy (workstream 07): /compte and components/account/*.

export const compteCopy = {
  meta: {
    title: "Mon compte",
    description: "Gérez vos informations personnelles, votre photo et votre type de compte.",
  },
  title: "Mon compte",
  subtitle: "Gérez vos informations personnelles, votre photo et votre type de compte.",
  header: {
    changePhoto: "Changer ma photo",
    uploading: "Envoi de la photo…",
    photoUpdated: "Photo mise à jour",
    photoTooLarge: "Photo trop volumineuse (5 Mo maximum).",
    photoType: "Formats acceptés : JPEG, PNG ou WebP.",
    photoFailed: "Impossible d'envoyer la photo. Réessayez.",
    roles: { CLIENT: "Client", PROVIDER: "Prestataire", ADMIN: "Admin" },
    memberSince: (date: string) => `Membre depuis ${date}`,
    unnamed: "Utilisateur KAYOU",
  },
  premium: {
    title: "Premium",
    tiers: { FREE: "Offre gratuite", VERIFIED: "Vérifié", BOOSTED: "Boosté", ELITE: "Élite" },
    description: "Gagnez en visibilité et rassurez vos clients.",
    action: "Premium",
  },
  quick: {
    title: "Accès rapide",
    reviews: { title: "Avis", description: "Voir mes avis" },
    orders: { title: "Mes commandes", description: "Suivi des prestations" },
    notifications: { title: "Notifications", description: "Activité récente" },
    help: { title: "Aide", description: "Questions fréquentes" },
    addresses: { title: "Mes adresses", description: "Lieux d'intervention" },
    space: { title: "Mon espace", description: "Demandes et planning" },
    earnings: { title: "Revenus", description: "Gains et transactions" },
    verification: { title: "Vérification", description: "Badge « Vérifié »" },
  },
  form: {
    title: "Informations personnelles",
    firstName: "Prénom",
    lastName: "Nom",
    phone: "Téléphone",
    phoneHint: "Votre numéro sert à vous connecter et ne peut pas être modifié ici.",
    city: "Ville",
    country: "Pays",
    countries: { RDC: "RD Congo", Congo: "Congo-Brazzaville" },
    gender: "Genre",
    genders: { "": "Non précisé", F: "Femme", M: "Homme", X: "Autre" },
    birthdate: "Date de naissance",
    bio: "Bio",
    bioPlaceholder: "Quelques mots sur vous…",
    counter: (n: number, max: number) => `${n}/${max}`,
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Profil mis à jour",
    nameRequired: "Le prénom et le nom sont obligatoires.",
  },
  becomeProvider: {
    title: "Devenir prestataire",
    description: "Publiez votre profil en quatre étapes et recevez des demandes.",
    action: "Commencer",
  },
  security: {
    title: "Sécurité & contrôle",
    logout: "Se déconnecter",
    logoutHint: "Vous pourrez vous reconnecter avec votre numéro.",
    delete: "Supprimer mon compte",
    deleteHint: "Supprime définitivement vos données personnelles.",
    deleteTitle: "Supprimer votre compte ?",
    deleteDescription: "Cette action est définitive. Vos réservations, messages et avis seront anonymisés.",
    deleteKeyword: "SUPPRIMER",
    deleteInputLabel: (keyword: string) => `Tapez ${keyword} pour confirmer`,
    deleteConfirm: "Supprimer définitivement",
    deleted: "Votre compte a été supprimé.",
  },
} as const;
