// Dev-only token page (/dev/tokens); deleted at the end of workstream 10.

export const devCopy = {
  title: "Design tokens",
  subtitle: "Palette, typographie, rayons, ombres, classes utilitaires et primitives de mouvement du shell K-YOU.",
  sections: {
    palette: "Palette",
    status: "Couleurs sémantiques",
    type: "Échelle typographique",
    radii: "Rayons",
    shadows: "Ombres",
    actions: "Actions",
    fields: "Champs",
    surfaces: "Surfaces",
    pills: "Pastilles de statut",
    skeleton: "Squelettes",
    motion: "Primitives de mouvement (framer-motion)",
    css: "Mouvement CSS",
  },
  samples: {
    heading: "Trouvez le bon professionnel près de chez vous",
    body: "Plombiers, électriciens, peintres, coiffeurs, garde d'enfants et plus encore.",
    caption: "Membre depuis septembre 2026",
    eyebrow: "RDC · Congo-Brazzaville",
    primary: "Réserver un créneau",
    gold: "Devenir prestataire",
    secondary: "Voir le profil",
    danger: "Annuler la réservation",
    disabled: "Indisponible",
    fieldLabel: "Quel service recherchez-vous ?",
    fieldPlaceholder: "Plombier, coiffeuse, électricien…",
    emptyTitle: "Aucune réservation",
    emptyDescription: "Vos réservations apparaîtront ici.",
    emptyAction: "Trouver un prestataire",
    metricLabel: "Réservations",
    metricValue: "12",
    tileTitle: "Aline Malu",
    tileMeta: "Ménage régulier · Kinshasa",
    dockDemo: "Indicateur du dock (layoutId)",
    sheetDemo: "Feuille inférieure",
    sheetOpen: "Ouvrir la feuille",
    sheetTitle: "Filtres",
    sheetBody: "Échap ferme la feuille, le focus reste à l'intérieur.",
    sheetClose: "Appliquer",
    wizardDemo: "Transition d'assistant",
    wizardPrev: "Précédent",
    wizardNext: "Suivant",
    wizardStep: (n: number) => `Étape ${n}`,
    listDemo: "Liste animée (layout)",
    listShuffle: "Mélanger",
    listRemove: "Retirer le premier",
    listReset: "Réinitialiser",
    pulse: "Touchez n'importe quel bouton : impulsion dorée de 38 px (désactivée en mouvement réduit).",
    screenEnter: "Chaque changement de route rejoue l'entrée d'écran de 240 ms.",
    hover: "Au survol (souris), l'ombre du bouton principal s'approfondit et l'image de la tuile grossit de 3,5 %.",
  },
  statuses: {
    confirmed: "Confirmée",
    pending: "En attente",
    cancelled: "Annulée",
    completed: "Terminée",
    elite: "Elite",
    messages: "Messages",
  },
} as const;
