// Messaging copy (workstream 07): /messagerie and components/messaging/*.

export const messagerieCopy = {
  meta: {
    title: "Messagerie",
    description: "Vos conversations avec les prestataires et les clients KAYOU.",
  },
  title: "Messages",
  subtitle: "Vos conversations avec les prestataires et les clients.",
  list: {
    label: "Conversations",
    more: "Voir plus",
    empty: {
      title: "Aucune conversation",
      description: "Écrivez à un prestataire depuis son profil pour démarrer une discussion.",
      action: "Rechercher",
    },
    unread: (count: number) => (count === 1 ? "1 message non lu" : `${count} messages non lus`),
    roles: { client: "Prestataire", provider: "Client" },
    noPreview: "Pièce jointe",
    deletedPreview: "Message supprimé",
  },
  thread: {
    back: "Retour aux conversations",
    provider: (name: string) => `Prestataire : ${name}`,
    client: (name: string) => `Client : ${name}`,
    defaultSubject: "Conversation",
    older: "Messages précédents",
    empty: "Aucun message pour l'instant. Écrivez le premier !",
    blocked: "Cette conversation est bloquée.",
    selectPrompt: "Sélectionnez une conversation pour l'afficher.",
    viewProfile: "Voir le profil",
    deleted: "Message supprimé",
    delete: "Supprimer",
    deleteTitle: "Supprimer ce message ?",
    deleteDescription: "Le message sera retiré pour tous les participants.",
    deleteConfirm: "Supprimer",
    deleted_toast: "Message supprimé",
    attachmentImage: "Image jointe",
    attachmentAudio: "Message vocal",
    attachmentLoading: "Chargement de la pièce jointe…",
    attachmentFailed: "Pièce jointe indisponible",
    openImage: "Agrandir l'image",
    closeImage: "Fermer",
    tip: "Restez sur KAYOU pour vos échanges : ne partagez jamais de code, de mot de passe ni de paiement en ligne.",
  },
  composer: {
    label: "Votre message",
    placeholder: "Écrivez votre message…",
    send: "Envoyer",
    sending: "Envoi…",
    empty: "Écrivez un message ou joignez un fichier.",
    blocked: "Impossible d'envoyer : l'un de vous a bloqué l'autre.",
    attachmentPreview: "Pièce jointe",
  },
  recorder: {
    record: "Enregistrer un message vocal",
    stop: "Terminer l'enregistrement",
    cancel: "Annuler l'enregistrement",
    confirm: "Joindre",
    recording: "Enregistrement",
    maxReached: "Durée maximale atteinte (2 min).",
    micUnavailable: "Micro inaccessible.",
    unsupported: "L'enregistrement audio n'est pas pris en charge par ce navigateur.",
  },
  safety: {
    report: "Signaler",
    block: "Bloquer",
    reportTitle: "Signaler cette conversation",
    reportLabel: "Décrivez le problème",
    reportPlaceholder: "Ex : propos déplacés, arnaque…",
    reportSubmit: "Envoyer le signalement",
    reportSent: "Signalement envoyé. Merci.",
    blockTitle: "Bloquer cet utilisateur ?",
    blockHint: "Il ne pourra plus vous écrire ni réserver avec vous. Vous pouvez annuler ce blocage plus tard.",
    blockConfirm: "Bloquer",
    blockCancel: "Annuler",
    blocked: "Utilisateur bloqué.",
  },
} as const;
