// Provider wizard, profile editor, schedule and media editors copy (workstream 06).

export const onboardingCopy = {
  meta: {
    title: "Devenir prestataire",
    description: "Publiez votre profil prestataire KAYOU en quatre étapes.",
  },
  hero: {
    title: "Devenez prestataire KAYOU",
    subtitle: "Développez votre activité et trouvez de nouveaux clients.",
  },
  steps: {
    label: "Progression",
    infos: "Informations personnelles",
    services: "Vos services",
    location: "Localisation",
    public: "Profil public",
    stepOf: (n: number, total: number) => `Étape ${n} sur ${total}`,
  },
  footer: {
    back: "Retour",
    next: "Continuer",
    submit: "Créer mon profil",
    submitting: "Publication…",
    uploading: "Envoi des fichiers en cours…",
  },
  infos: {
    title: "Informations personnelles",
    displayName: "Nom d'affichage",
    displayNamePlaceholder: "Ex. : Jean Dupont",
    phone: "Téléphone",
    whatsapp: "WhatsApp",
    whatsappHint: "Facultatif. Laissez vide si identique.",
    photo: "Photo de profil",
    photoHint: "Montrez votre visage pour inspirer confiance.",
  },
  services: {
    title: "Vos services",
    category: "Catégorie",
    subcategory: "Sous-catégorie",
    service: "Service",
    experience: "Années d'expérience",
    skills: "Compétences",
    freeSkills: "Autres compétences",
    freeSkillsPlaceholder: "Ex. : carrelage, plomberie sanitaire (séparées par des virgules)",
    freeSkillsHint: (n: number, max: number) => `${n}/${max} compétences libres`,
    description: "Description",
    descriptionPlaceholder: "Présentez votre activité, vos réalisations, vos garanties…",
    counter: (n: number, max: number) => `${n}/${max}`,
  },
  location: {
    title: "Localisation",
    address: "Adresse",
    addressPlaceholder: "Rue, avenue, point de repère…",
    gpsHint: "La position affine la recherche « autour de moi ».",
  },
  public: {
    title: "Profil public",
    languages: "Langues parlées",
    modes: "Mode d'intervention",
    gallery: "Photos de vos réalisations",
    galleryHint: (n: number, max: number) => `${n}/${max} photos · JPEG, PNG ou WebP, 8 Mo max`,
    social: "Réseaux sociaux",
    socialHint: "Liens publics vers vos pages (facultatif).",
    youtube: "Chaîne YouTube",
    instagram: "Instagram",
    tiktok: "TikTok",
    facebook: "Facebook",
    preview: "Aperçu de votre carte",
    terms: {
      accept: "J'accepte les",
      cgu: "conditions générales d'utilisation",
      and: "et la",
      privacy: "politique de confidentialité",
      end: "de KAYOU.",
    },
    benefits: {
      title: "Avec KAYOU, vous bénéficiez de :",
      requests: "Recevez des demandes",
      schedule: "Gérez votre planning",
      visible: "Soyez visible localement",
    },
  },
  preview: {
    empty: "—",
    separator: " · ",
  },
  success: {
    title: "Votre profil est en ligne",
    subtitle: "Redirection vers votre profil…",
  },
  errors: {
    publishFailed: "La publication a échoué. Vérifiez les champs signalés.",
    alreadyProvider: "Vous avez déjà un profil prestataire. Redirection vers l'éditeur…",
    fieldInvalid: "Champ invalide",
    stepInvalid: (step: string) => `Corrigez l'étape « ${step} ».`,
  },
  validation: {
    displayName: "Le nom d'affichage doit contenir entre 2 et 120 caractères.",
    phone: "Numéro de téléphone invalide.",
    whatsapp: "Numéro WhatsApp invalide.",
    category: "Choisissez votre service dans la liste.",
    city: "Choisissez au moins une ville.",
    terms: "Acceptez les conditions pour publier.",
    uploading: "Attendez la fin des envois de fichiers.",
    schedule: "Corrigez votre planning.",
  },
  photo: {
    add: "Ajouter une photo",
    addMany: "Ajouter des photos",
    replace: "Changer la photo",
    remove: "Retirer la photo",
    retry: "Réessayer",
    hint: "JPEG, PNG ou WebP · 8 Mo max",
    tooLarge: "Image trop volumineuse (8 Mo maximum).",
    badType: "Format non pris en charge. Utilisez JPEG, PNG ou WebP.",
    tooMany: (max: number) => `${max} photos maximum.`,
    uploadFailed: "L'envoi a échoué. Réessayez.",
    uploading: (pct: number) => `Envoi : ${pct} %`,
    alt: "Aperçu",
  },
  video: {
    title: "Mes vidéos",
    count: (n: number, max: number) => `${n}/${max}`,
    youtubeTab: "Lien YouTube",
    uploadTab: "Ma galerie",
    urlLabel: "Lien de la vidéo",
    urlPlaceholder: "https://youtu.be/…",
    urlHint: "Lien attendu : vidéo YouTube, Shorts ou youtu.be.",
    addYoutube: "Ajouter cette vidéo",
    upload: "Ajouter une vidéo",
    uploadHint: "MP4, MOV ou WebM · 25 Mo max",
    tooLarge: "Vidéo trop volumineuse (25 Mo maximum).",
    badType: "Format non pris en charge. Utilisez MP4, MOV ou WebM.",
    duplicate: "Cette vidéo est déjà ajoutée.",
    tooMany: (max: number) => `${max} vidéos maximum.`,
    uploadFailed: "L'envoi a échoué. Réessayez.",
    uploading: (pct: number) => `Envoi : ${pct} %`,
    processing: "Traitement de la vidéo…",
    remove: "Supprimer",
    removeConfirm: "Supprimer cette vidéo ?",
    dragHandle: "Réordonner",
    moveUp: "Déplacer avant",
    moveDown: "Déplacer après",
    thumbnailAlt: "Aperçu de la vidéo",
    retry: "Réessayer",
  },
  schedule: {
    title: "Mon planning",
    timezone: "Fuseau horaire",
    timezones: {
      "Africa/Kinshasa": "Kinshasa · UTC+1",
      "Africa/Lubumbashi": "Lubumbashi · UTC+2",
      "Africa/Brazzaville": "Brazzaville · UTC+1",
    },
    duration: "Durée du rendez-vous",
    buffer: "Marge entre rendez-vous",
    minutes: (n: number) => `${n} min`,
    durationHint: "Durée commune aux réservations de ce profil. Les réservations existantes conservent leur durée.",
    days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
    open: (day: string) => `Ouvert le ${day.toLowerCase()}`,
    closed: "Fermé",
    copyWeek: "Copier lun–ven",
    start: "Heure de début",
    end: "Heure de fin",
    removeRange: "Supprimer la plage",
    addRange: "+ Plage",
    maxRanges: (n: number) => `${n} plages maximum par jour`,
    exceptions: "Congés et jours exceptionnels",
    exceptionDate: "Date",
    exceptionClosed: "Fermé ce jour",
    exceptionOpen: "Horaires spéciaux",
    exceptionReason: "Motif (facultatif)",
    exceptionReasonPlaceholder: "Ex. : jour férié",
    addException: "+ Exception",
    removeException: "Retirer l'exception",
    duplicateDate: "Une seule exception par date.",
    errorsTitle: "Corrigez votre planning :",
  },
  editor: {
    meta: { title: "Modifier mon profil" },
    title: "Modifier mon profil",
    subtitle: "Chaque onglet s'enregistre séparément.",
    back: "Retour à mon espace",
    viewProfile: "Voir mon profil public",
    tabs: {
      label: "Sections du profil",
      infos: "Infos",
      services: "Services",
      location: "Localisation",
      public: "Profil public",
      schedule: "Planning",
      media: "Vidéos",
    },
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Modifications enregistrées.",
    dirty: "Modifications non enregistrées",
    dirtyGuard: "Vous avez des modifications non enregistrées. Changer d'onglet sans enregistrer ?",
    scheduleNotice: "Modifier le planning n'annule pas les réservations existantes.",
    mediaTitle: "Vidéos et photos",
    unavailable: "Profil introuvable ou accès refusé.",
    admin: {
      title: "Modération",
      readOnly: "En tant qu'administrateur, les contenus sont en lecture seule. Seule la modération est modifiable ici.",
      hidden: "Profil masqué",
      hiddenHint: "Un profil masqué disparaît de la recherche et n'est visible que par son propriétaire.",
      tier: "Offre",
      tiers: { FREE: "Gratuit", VERIFIED: "Vérifié", BOOSTED: "Boosté", ELITE: "Elite" },
      verification: "Vérification",
      statuses: { PENDING: "En attente", UNDER_REVIEW: "En cours d'examen", VERIFIED: "Vérifié", REJECTED: "Refusé" },
      rejectionReason: "Motif du refus",
      save: "Enregistrer la modération",
    },
  },
} as const;
