// Provider profile copy (workstream 05). Shared components (booking, composer, review, login wall) live here too.

export const providerCopy = {
  meta: {
    title: (name: string) => `${name} — prestataire sur KAYOU`,
    description: (name: string, specialty: string, city: string) =>
      `${name}, ${specialty} à ${city}. Avis clients, réalisations, horaires et réservation sur KAYOU.`,
  },
  back: "Rechercher",
  header: {
    experience: (years: number) => (years === 1 ? "1 an d'expérience" : `${years} ans d'expérience`),
    reviews: (n: number) => (n === 1 ? "1 avis" : `${n} avis`),
    noRating: "—",
    photoAlt: (name: string) => `Photo de ${name}`,
    countryRdc: "RDC",
    countryCongo: "Congo",
    ownerHint: "Ceci est votre profil public.",
    edit: "Modifier mon profil",
  },
  tier: {
    verified: "Vérifié",
    boosted: "Boosté",
    elite: "Elite",
  },
  contact: {
    message: "Envoyer un message",
    call: "Appeler",
    whatsapp: "WhatsApp",
    locked: "Contacts verrouillés",
    lockedHint: "Ce prestataire ne partage ses coordonnées qu'avec les membres Premium.",
    lockedCta: "Découvrir Premium",
    blocked: "Les échanges avec ce prestataire sont désactivés.",
    maskedNumber: "••• •• •• ••",
  },
  distance: {
    label: "Votre adresse",
    placeholder: "Estimer la distance depuis une adresse…",
    hint: "Choisissez une adresse pour estimer la distance.",
  },
  gallery: {
    title: "Réalisations",
    empty: "Aucune photo pour le moment.",
    open: (n: number) => `Ouvrir la photo ${n}`,
    close: "Fermer",
    previous: "Photo précédente",
    next: "Photo suivante",
    lightbox: "Photo en grand",
  },
  social: {
    title: "Réseaux sociaux",
    open: "Ouvrir",
    youtube: "YouTube",
    instagram: "Instagram",
    tiktok: "TikTok",
    facebook: "Facebook",
  },
  videos: {
    title: "Vidéos",
    play: "Lire la vidéo YouTube",
    openYoutube: "Ouvrir sur YouTube",
    thumbnailAlt: "Aperçu de la vidéo",
    unavailable: "Vidéo indisponible.",
    fallback: "Lecture non disponible.",
  },
  choices: {
    languages: "Langues parlées",
    modes: "Modes d'intervention",
    pricing: "Tarif indicatif",
    pricingFrom: (amount: string, unit: string) => `à partir de ${amount} · ${unit}`,
    pricingHint: "Tarif indicatif, à confirmer avec le prestataire.",
  },
  skills: {
    title: "Compétences",
  },
  reviews: {
    title: (n: number) => `Avis clients (${n})`,
    empty: "Aucun avis pour le moment.",
    emptyHint: "Les avis apparaissent après une prestation terminée.",
    reply: "Réponse du prestataire",
  },
  schedule: {
    title: "Horaires",
    closed: "Fermé",
    exceptions: "Prochaines exceptions",
    exceptionClosed: "Fermé",
    exceptionOpen: (from: string, to: string) => `Ouvert ${from}–${to}`,
    days: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
  },
  address: {
    title: "Adresse",
    directions: "Itinéraire",
  },
  safety: {
    report: "Signaler",
    block: "Bloquer",
    reportTitle: "Signaler ce prestataire",
    reportLabel: "Que souhaitez-vous signaler ?",
    reportPlaceholder: "Décrivez le problème en quelques mots…",
    reportSubmit: "Envoyer le signalement",
    reportSent: "Signalement envoyé à notre équipe.",
    blockTitle: "Bloquer ce prestataire",
    blockHint:
      "Vous ne pourrez plus échanger de messages ni réserver avec ce prestataire. Cette action est réversible depuis votre compte.",
    blockConfirm: "Confirmer le blocage",
    blockCancel: "Annuler",
    blocked: "Prestataire bloqué. Les échanges sont désormais désactivés.",
  },
  booking: {
    title: "Réserver un créneau",
    disabled: "Réservations temporairement désactivées.",
    providerRole: "Les réservations se font depuis un compte client.",
    date: "Date",
    slots: "Créneau",
    slotsEmpty: "Aucun créneau ce jour",
    slotsError: "Créneaux indisponibles. Choisissez une autre date.",
    timezone: (tz: string) => `Horaires : ${tz}`,
    phone: "Votre téléphone",
    phoneInvalid: "Numéro international invalide (ex. +243 …).",
    addressTitle: "Adresse de la prestation",
    addressDefault: "Mon adresse par défaut",
    addressSaved: "Une autre adresse enregistrée",
    addressNew: "Une nouvelle adresse",
    addressNone: "Sans adresse",
    addressPick: "Choisir une adresse",
    addressLine: "Adresse",
    notes: "Précisions (optionnel)",
    notesPlaceholder: "Étage, accès, détails utiles…",
    submit: "Confirmer la réservation",
    submitting: "Envoi…",
    successTitle: "Créneau réservé",
    successBody: (when: string) => `Votre demande pour ${when} est envoyée. Le prestataire confirme rapidement.`,
    successLink: "Voir mes réservations",
    another: "Réserver un autre créneau",
    slotTaken: "Ce créneau vient d'être pris. Choisissez-en un autre.",
    unavailable: "Ce prestataire ne prend pas de réservations pour le moment.",
  },
  composer: {
    title: (name: string) => `Écrire à ${name}`,
    subject: "Sujet (optionnel)",
    subjectPlaceholder: "Ex : Devis peinture salon",
    body: "Message",
    bodyPlaceholder: "Décrivez votre besoin…",
    counter: (n: number, max: number) => `${n}/${max}`,
    cancel: "Annuler",
    send: "Envoyer",
    sending: "Envoi…",
    empty: "Écrivez un message ou joignez un fichier.",
    blocked: "Impossible d'envoyer : l'un de vous a bloqué l'autre.",
    attachments: {
      image: "Joindre une image",
      record: "Enregistrer un message vocal",
      stop: "Arrêter l'enregistrement",
      recording: "Enregistrement…",
      remove: "Retirer",
      uploading: "Envoi du fichier…",
      tooLarge: "Fichier trop volumineux (8 Mo maximum).",
      tooMany: "6 pièces jointes maximum.",
      uploadFailed: "Échec de l'envoi du fichier. Le brouillon est conservé.",
      micUnavailable: "Micro inaccessible.",
      audioLabel: "Message vocal",
    },
  },
  review: {
    title: "Laisser un avis",
    disabled: "Avis temporairement désactivés.",
    rating: "Votre note",
    comment: "Votre commentaire",
    commentPlaceholder: "Racontez votre expérience…",
    counter: (n: number, max: number) => `${n}/${max}`,
    submit: "Publier mon avis",
    submitting: "Envoi…",
    needsBooking: "Vous pourrez laisser un avis après une prestation terminée avec ce prestataire.",
    alreadyReviewed: "Vous avez déjà noté ce prestataire.",
    providerRole: "Les avis se laissent depuis un compte client.",
    thanks: "Merci pour votre avis !",
    star: (n: number) => (n === 1 ? "1 étoile" : `${n} étoiles`),
  },
  loginWall: {
    title: "Connectez-vous pour continuer",
    description: "Les coordonnées, la réservation et les avis sont réservés aux membres.",
    login: "Connexion",
    register: "Créer un compte",
  },
  expandable: {
    more: "Voir plus",
    less: "Voir moins",
  },
  phoneField: {
    prefix: "Indicatif",
    number: "Numéro de téléphone",
    placeholder: "Numéro",
    otherPlaceholder: "+…",
    countries: [
      { value: "+243", label: "RDC +243" },
      { value: "+242", label: "Congo +242" },
      { value: "+33", label: "France +33" },
      { value: "+32", label: "Belgique +32" },
      { value: "+1", label: "USA/CA +1" },
    ],
    other: "Autre",
  },
  geo: {
    verified: (lat: string, lng: string) => `Vérifié GPS : ${lat}, ${lng}`,
    searching: "Recherche…",
    notFound: "Adresse introuvable.",
    useMyPosition: "Utiliser ma position",
    positionLabel: "Ma position actuelle",
    positionFailed: "Position indisponible.",
  },
  references: {
    choose: "Choisir…",
    search: (label: string) => `Rechercher : ${label}`,
    searchPlaceholder: "Rechercher…",
    kept: "Choix conservé · à vérifier",
    unavailable: "Listes indisponibles. Réessayez plus tard.",
    kinds: {
      COUNTRY: "Pays",
      PROVINCE: "Province",
      CITY: "Ville",
      TERRITORY: "Territoire",
      COMMUNE: "Commune",
      SECTOR: "Secteur",
      CHIEFDOM: "Chefferie",
      QUARTIER: "Quartier",
      VILLAGE: "Village",
    },
    missingPlace: "Mon lieu est absent",
    suggestKind: "Type de lieu proposé",
    suggestLabel: "Nom du lieu",
    suggestSubmit: "Proposer",
    suggestSent: "Proposition envoyée pour validation.",
    suggestLogin: "Connectez-vous pour proposer un lieu.",
    pricingToggle: "Afficher un tarif indicatif",
    pricingAmount: "Montant",
    pricingCurrency: "Devise",
    pricingUnit: "Unité",
    multiSearch: "Rechercher un choix…",
  },
} as const;
