// Search copy (workstream 05).

export const searchCopy = {
  meta: {
    title: "Rechercher un prestataire",
    description: "Trouvez un prestataire vérifié par service et par lieu en RDC et au Congo-Brazzaville.",
  },
  title: "Trouver un prestataire",
  searchPlaceholder: "Quel service recherchez-vous ?",
  searchLabel: "Rechercher un service",
  nearMe: "À proximité",
  locating: "Localisation…",
  positionOn: "Position activée",
  filters: "Filtres",
  filtersOpen: "Ouvrir les filtres",
  clearAll: "Effacer les filtres",
  activeFilters: (n: number) => (n === 1 ? "1 filtre actif" : `${n} filtres actifs`),
  results: (n: number) => (n === 1 ? "1 prestataire trouvé" : `${n} prestataires trouvés`),
  resultsMore: (n: number) => `${n}+ prestataires trouvés`,
  searching: "Recherche en cours",
  view: {
    label: "Affichage",
    list: "Liste",
    map: "Carte",
  },
  interpretation: {
    label: (name: string) => `Inclut aussi : ${name}`,
    remove: (name: string) => `Retirer ${name} de la recherche`,
  },
  loadMore: "Voir plus",
  loadingMore: "Chargement…",
  empty: {
    title: "Aucun prestataire pour ces critères",
    description: "Élargissez votre recherche ou réinitialisez les filtres.",
    action: "Réinitialiser",
  },
  errors: {
    unavailable: "Recherche indisponible. Vérifiez votre connexion et réessayez.",
    locationDenied: "Position refusée",
    locationUnavailable: "Position indisponible",
  },
  sheet: {
    title: "Filtres",
    close: "Fermer les filtres",
    category: "Catégorie",
    subcategory: "Spécialité",
    service: "Service",
    allCategories: "Toutes les catégories",
    allSubcategories: "Toutes les spécialités",
    allServices: "Tous les services",
    language: "Langue parlée",
    mode: "Mode d'intervention",
    sort: "Trier par",
    sortOptions: {
      recommended: "Recommandé",
      rating: "Note",
      distance: "Distance",
      newest: "Nouveaux",
    },
    minRating: "Note minimale",
    ratingAll: "Toutes",
    premiumOnly: "Premium uniquement",
    premiumOnlyHint: "Prestataires boostés / élite",
    verifiedOnly: "Vérifiés uniquement",
    verifiedOnlyHint: "Profils vérifiés par KAYOU",
    reset: "Réinitialiser",
    apply: "Appliquer",
    distanceNeedsPosition: "Activez « À proximité » pour trier par distance.",
  },
  map: {
    youAreHere: "Vous êtes ici",
    viewProfile: "Voir le profil",
    attribution: "© OpenStreetMap",
    label: "Carte des prestataires",
  },
  card: {
    viewProfile: "Voir le profil →",
    noRating: "—",
    reviews: (n: number) => (n === 1 ? "1 avis" : `${n} avis`),
  },
} as const;
