// Shell copy (workstream 04). Plain objects only; components never inline French.

export const shellCopy = {
  brand: "KAYOU",
  meta: {
    title: "KAYOU — Trouvez le bon professionnel près de chez vous",
    description:
      "KAYOU connecte les clients aux prestataires de services vérifiés en RDC et au Congo-Brazzaville : plomberie, électricité, ménage, beauté et plus encore.",
  },
  nav: {
    home: "Accueil",
    search: "Rechercher",
    services: "Tous les services",
    premium: "Premium",
    becomeProvider: "Devenir prestataire",
    messages: "Messages",
    myBookings: "Mes réservations",
    mySpace: "Mon espace",
    admin: "Admin",
    login: "Connexion",
    logout: "Déconnexion",
    account: "Mon compte",
    notifications: "Notifications",
    mainNav: "Navigation principale",
  },
  dock: {
    label: "Navigation mobile",
    home: "Accueil",
    explore: "Explorer",
    services: "Services",
    login: "Connexion",
    orders: "Commandes",
    messages: "Messages",
    profile: "Profil",
    requests: "Demandes",
    earnings: "Revenus",
  },
  footer: {
    nav: "Informations utiles",
    contact: "Contact",
    privacy: "Confidentialité",
    terms: "Conditions",
  },
  offline: {
    offline: "Vous êtes hors ligne. Les actions reprendront à la reconnexion.",
    online: "Connexion rétablie.",
  },
  maintenance: {
    fallback: "KAYOU est en maintenance. Certaines actions sont temporairement indisponibles.",
  },
  loading: "Chargement",
  suspended: {
    title: "Compte suspendu",
    description: "Votre compte a été suspendu par un administrateur.",
    reason: "Motif",
    support: "Pour toute question, contactez le support de KAYOU.",
    logout: "Se déconnecter",
  },
  acceptTerms: {
    eyebrow: "Une dernière étape",
    title: "Avant de continuer",
    description:
      "Pour utiliser KAYOU, merci de lire et d'accepter nos conditions générales d'utilisation et notre politique de confidentialité.",
    terms: "Conditions générales d'utilisation",
    privacy: "Politique de confidentialité",
    action: "J'accepte et je continue",
    error: "Impossible d'enregistrer votre accord. Réessayez.",
  },
  canvas: {
    skip: "Passer",
  },
  sheet: {
    close: "Fermer",
  },
  screenTitles: {
    home: "Accueil",
    search: "Rechercher",
    services: "Tous les services",
    premium: "Premium",
    contact: "Contact",
    cgu: "Conditions générales d'utilisation",
    privacy: "Politique de confidentialité",
    welcome: "Bienvenue",
    login: "Connexion",
    register: "Créer un compte",
    becomeProvider: "Devenir prestataire",
    provider: "Prestataire",
    editProvider: "Modifier mon profil",
    mySpace: "Mon espace",
    myBookings: "Mes réservations",
    booking: "Réservation",
    messaging: "Messagerie",
    earnings: "Revenus",
    reviews: "Avis",
    notifications: "Notifications",
    help: "Aide",
    addresses: "Adresses",
    account: "Compte",
    verification: "Vérification",
    admin: "Admin",
    devTokens: "Design tokens",
  },
  admin: {
    title: "KAYOU ADMIN",
    subtitle: "L'espace de pilotage",
    nav: "Sections d'administration",
    breadcrumb: "Centre de contrôle",
    secure: "Accès sécurisé",
  },
  notFound: {
    eyebrow: "Erreur 404",
    title: "Page introuvable",
    description: "La page que vous cherchez n'existe pas ou a été déplacée.",
    action: "Retour à l'accueil",
  },
  placeholder: {
    eyebrow: "Écran à venir",
    description: (workstream: string) =>
      `Cet écran est livré par le chantier ${workstream} de la refonte K-YOU.`,
    back: "Retour à l'accueil",
  },
  homePlaceholder: {
    eyebrow: "RDC · Congo-Brazzaville",
    title: "Trouvez le bon professionnel près de",
    titleAccent: "chez vous",
    subtitle:
      "Plombiers, électriciens, peintres, coiffeurs, garde d'enfants et plus encore, partout en RDC et au Congo-Brazzaville.",
    searchPlaceholder: "Quel service recherchez-vous ?",
    searchAction: "Rechercher",
    trust: ["Vérifié", "Avis clients", "Réservation simple"],
    tiles: {
      search: { title: "Rechercher", description: "Trouvez un prestataire par service et par lieu." },
      services: { title: "Tous les services", description: "Parcourez les 19 catégories." },
      provider: { title: "Devenir prestataire", description: "Publiez votre profil en quatre étapes." },
    },
  },
} as const;
